gun = int(input("amount of gun: "))
gun_cost = int(input("cost of gun:"))
gun_price = int(input("price of gun:"))
team_member = int(input("member:"))
print(gun_cost*gun)
print(gun_price*gun)
print(gun_price*gun - gun_cost*gun)
x = (gun_price*gun - gun_cost*gun)
print(x *2/10)
print(x *2/50)