gun = int(input("amount of gun: "))
gun_cost = int(input("cost of gun:"))
gun_price = int(input("price of gun:"))
team_member = int(input("member:"))
print(gun_cost*gun)
print(gun_price*gun)
print(gun_price*gun - gun_cost*gun)
profit = (gun_price*gun - gun_cost*gun)
print(profit *20/100)
boss_percent = (profit *20/100)
share_member = (profit - boss_percent) / 5
print(share_member)